### ISSUE TITLE
Can I add your app to React Native Apps repository?

### ISSUE THREAD

**Issue by shoken0x** [GetStream/slack-clone-react-native#1]
It's nice OSS React Native App. I think it would be helpful to other developers. Can I add your app to React Native Apps repository?
https://github.com/ReactNativeNews/React-Native-Apps

**Comment by vishalnarkhede** [comment]
Hey @shoken0x go for it. Thanks :)

**Comment by shoken0x** [comment]
Hey @vishalnarkhede , I pushed [pull request](https://github.com/ReactNativeNews/React-Native-Apps/pull/131) and merged. 🎉
